version: "3"

services:
#  proxy:
#    build: nginx/
#    container_name: "portainer-proxy"
#    ports:
#    - "80:80"
#    networks:
#    - local

  templates:
    image: portainer/templates
    container_name: "portainer-templates"
    restart: always
    environment:
    - TZ=America/Chicago
    networks:
    - local

  portainer:
    image: portainer/portainer
    container_name: "portainer-app"
    command: --templates http://templates/templates.json --host=unix:///var/run/docker.sock
    privileged: true
    restart: always
    environment:
    - TZ=America/Chicago
    networks:
    - local
    ports:
    - 9000:9000
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /data/portainer:/data

  watchtower:
    image: v2tec/watchtower
    container_name: "portainer-watchtower"
    command: --cleanup portainer-app portainer-watchtower portainer/templates
    privileged: true
    restart: always
    environment:
    #- PUID=1000
    #- PGID=1000
    - TZ=America/Chicago
    networks:
    - local
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock

  mariadb:
    image: linuxserver/mariadb
    restart: always
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=America/Chicago
    env_file:
    - /opt/bb-file-server/.secrets/mysql.env
    networks:
    - web
    - local
    ports:
    - 3306:3306
    volumes:
    - /data/mariadb:/config

  guacd:
    image: guacamole/guacd
    restart: always
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=America/Chicago
    networks:
    - web
    - local
#    - hostnet

  guac:
    image: guacamole/guacamole
    restart: always
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=America/Chicago
    - MYSQL_HOSTNAME=mariadb
    - MYSQL_PORT=3306
    - MYSQL_DATABASE=guacamole
    - MYSQL_USER=root
    - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - GUACD_HOSTNAME=guacd
    - GUACD_PORT=4822
    depends_on:
    - mariadb
    - guacd
    networks:
    - web
    - local
    ports:
    - 8080:8080



  duckdns:
    image: linuxserver/duckdns
    restart: always
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=America/Chicago
    env_file:
    - /opt/bb-file-server/.secrets/duckdns.env

  openvpn:
    image: linuxserver/openvpn-as
    network_mode: host
    privileged: true
    restart: always
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=America/Chicago
    #- INTERFACE=enp0s31f6
    - INTERFACE=bridge0
    #ports:
    #- 943:943
    #- 9443:9443
    #- 1194:1194
    volumes:
    - /data/openvpn-as:/config

  resilio:
    image: linuxserver/resilio-sync
    #network_mode: host
    privileged: true
    restart: always
    environment:
    - PUID=0
    - PGID=0
    - TZ=America/Chicago
    ports:
    - 8888:8888
    - 55555:55555
    - 1900:1900
    - 5351:5351
    - 3838:3838
    - 4000:4000
    - 3000:3000
    - 3001:3001
    - 4000:4000/udp
    - 3000:3000/udp
    - 3001:3001/udp
    volumes:
    - /data/resilio-sync/config:/config
    - /data/resilio-sync/folders:/sync

  syncthing:
    image: linuxserver/syncthing
    network_mode: host
    privileged: true
    restart: always
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=America/Chicago
    #ports:
    #- 8384:8384
    #- 21027:21027
    #- 22000:22000
    volumes:
    - /data/syncthing/config:/config
    - /data/syncthing/folders:/sync

  freshrss:
    image: linuxserver/freshrss
    restart: always
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=America/Chicago
    links:
    - mariadb
    networks:
    - web
    #ports:
    #- 8080:80
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /data/freshrss:/config

  letsencrypt:
    image: linuxserver/letsencrypt
    # network_mode: host
    restart: always
    env_file:
    - /opt/bb-file-server/.secrets/letsencrypt.env
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=America/Chicago
    - URL=duckdns.org
    - ONLY_SUBDOMAINS=true
    - DHLEVEL=2048
    networks:
    - web
    ports:
    - 443:443
    volumes:
    - /data/letsencrypt:/config

  oauth-firewall:
    image: oauth-firewall
    restart: always
    build:
      context: /opt/bb-file-server/oauth-firewall/
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=America/Chicago
    networks:
    - web
    #ports:
    #- 4180:4180
    volumes:
    - /data/oauth-firewall/:/opt/oauth2-proxy/etc/
    #- /data/oauth-firewall:/config
    command:
    - -http-address=http://0.0.0.0:4180
    - -redirect-url=${OAUTH_REDIRECT_URL}
    - -upstream=file:///dev/null
    - -provider=google
    - -ssl-insecure-skip-verify=true
    - -client-id=${OAUTH_CLIENT_ID}
    - -client-secret=${OAUTH_CLIENT_SECRET}
    - -authenticated-emails-file=/opt/oauth2-proxy/etc/authorized_emails
    - -cookie-expire=4h
    - -cookie-refresh=1h
    - -cookie-secret=${OAUTH_COOKIE_SECRET}
    - -cookie-secure=true
    - -cookie-httponly=false
    # - -cookie-domain=something.duckdns.org
    # - -https-address=https://0.0.0.0:443

  # -redirect-url : Defaults to the "https://" + requested host header + "/oauth2/callback".
  # -upstream: It should never use the upstream since we are only going to talk with the OAuth2 Proxy when we need to auth.
  # -cookie-httponly: HttpOnly - httponly cookies are not readable by javascript (recommended).

  plex:
    # image: linuxserver/plex
    # image: uirel/lsio-plex-comskip
    # build: ./docker/plex
    build: https://github.com/Poag/lsio-plex-comskip.git
    restart: always
    privileged: true
    network_mode: host
    #network_mode: bridge
    #ports:
    #- 32400:32400
    #- 32400:32400/udp
    #- 32469:32469
    #- 32469:32469/udp
    #- 5354:5353/udp
    #- 1900:1900/udp
    environment:
    - PUID=0
    - PLEX_UID=0
    - PGID=0
    - PLEX_GID=0
    - TZ=America/Chicago
    - VERSION=latest
    - HOSTNAME=${HOSTNAME}
    #- PLEX_CLAIM=...
    volumes:
    - /data/plex/config:/config
    - /data/media:/data
    - /data/plex/transcode:/transcode

networks:
  hostnet:
    external:
      name: host
  local:
    driver: bridge
  web:

# secrets:
#   mysql_root_pass:
#     file: /opt/bb-file-server/.secrets/mysql_root_pass.txt

